---
title: "hsls_MAR"
format: html
editor: visual
---

```{r}
library(dplyr)
library(ggplot2)
library(gridExtra)
library(psych)
library(tidyr)

dathsls <- haven::read_sav("HSLS6.11.21.sav")

hsls <- dathsls

hsls <- hsls %>%
  rename(stu_id = STU_ID, # change column names
         sch_id = SCH_ID,
         # excellentTests = S1MTESTS,
         # understandTexts = S1MTEXTBOOK,
         # masterSkills = S1MSKILLS,
         # excellentAssign = S1MASSEXCL,
         # sex = X1SEX,
         race = X1RACE,
         hispanic = X1HISPANIC,
         white = X1WHITE,
         black = X1BLACK,
         asian = X1ASIAN,
         pacificIsland = X1PACISLE,
         SES = X1SES,
         hsls_w_cohort_g9 = W1STUDENT,
         hsls_w_cohort_g12 = W2STUDENT)

hsls <- dathsls %>%
  rename(math_theta1 = X2TXMTH,
         math_theta2 = X1TXMTH)

```


```{r}

na_proportions_gender_poverty <- hsls %>%
  filter(!is.na(S1MENJOYING)) %>%
  filter(!is.na(X1POVERTY)) %>% 
  group_by(S1MENJOYING, X1SEX, X1POVERTY) %>%
  summarize(na_prop = mean(is.na(S2MTESTS))) %>%
  ungroup()

na_proportions_gender <- hsls %>%
  filter(!is.na(S1MENJOYING)) %>%
  group_by(S1MENJOYING, X1SEX) %>%
  summarize(na_prop = mean(is.na(S2MTESTS))) %>%
  ungroup()


likert_order <- c("Strongly disagree", "Disagree", "Agree", "Strongly agree")

# Create a bar plot
plot_prop_gender <- ggplot(na_proportions_gender, aes(x = as.factor(S1MENJOYING), y = na_prop, group = X1SEX, color = as.factor(X1SEX))) +
  geom_line(size = 1.2) +
  geom_point(size = 3) +
  labs(x = "S1MENJOYING (Likert Response)", y = "Proportion of NA's in S2MTESTS", color = "Gender") +
  ggtitle("Proportion of NA's in S2MTESTS by S1MENJOYING Response and Gender") +
  theme_minimal()

plot_prop_gender

```

```{r}

hsls$S2MTESTS_na <- ifelse(is.na(hsls$S2MTESTS), 1, 0)

log_reg_a <- glm(S2MTESTS_na ~ S1MENJOYING * X1SEX, 
                         data = hsls, 
                         family = "binomial")

summary(log_reg_a)



```

```{r}

ggplot(na_proportions_gender_poverty, aes(x = as.factor(S1MENJOYING), y = na_prop, group = X1SEX, color = as.factor(X1SEX))) +
  geom_line(size = 1.2) +
  geom_point(size = 3) +
  labs(x = "S1MENJOYING (Likert Response)", y = "Proportion of NA's in S2MTESTS", color = "Gender") +
  ggtitle("Proportion of NA's in S2MTESTS by S1MENJOYING Response, Gender, and Poverty Status") +
  theme_minimal() +
  facet_wrap(~X1POVERTY, labeller = label_both)


log_reg_b <- glm(S2MTESTS_na ~ S1MENJOYING * X1SEX * X1POVERTY, 
                         data = hsls, 
                         family = "binomial")

summary(log_reg_b)


```

